baseURL = "http://www.sayaka.work"
UglyURLs = true 
languageCode = "en-us"
title = "新婚夫婦日記"
theme = "hugo-zen"
googleAnalytics = "UA-146219040-1"
copyright = "sayaka.work"

[params]
  logo      = "/images/logo.jpg"
#  twitter   = "https://twitter.com/syk5817"
#facebook  = "https://www.facebook.com/ochiishikoichiro"
#github    = "https://github.com/rakuishi/"
#gitlab    = "https://gitlab.com/rakuishi/"
#email     = "rakuishi@gmail.com"
